image: Visual Studio 2019
# branches:
#  only:
# - master
version: '{build}'
cache:
  - c:\Tools\vcpkg\installed
install:
  - cd c:\tools\vcpkg
  - vcpkg integrate install
  - vcpkg install zap
  - set PATH_COPY=%PATH%
  - set PATH=%PATH%;c:\tools\vcpkg\installed\x86-windows\tools\zap
  - cd %APPVEYOR_BUILD_FOLDER%
  - dotnet tool install -g nbgv --version 3.4.240
  - choco install reportgenerator.portable --version=4.5.6 --force -y
  - dotnet tool install -g coveralls.net --version 1.0.0
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
environment:
  COVERALLS_REPO_TOKEN:
    secure: mwxwOymoS7vB56iQN5Obbt8+oMqbRpK8Ei2GZUI7Mm46C8asDR/Wu0RAXYlhp85Q
  MSBUILDSINGLELOADCONTEXT: '1'
before_build:
  - cmd: nbgv cloud
  - cmd: dotnet --version
  - cmd: msbuild -ver
  - cmd: dotnet restore ./Zap.Net.Runtime/Zap.Net.Runtime.csproj --verbosity m
  - cmd: dotnet restore ./Zap.Net.Runtime.Tests/Zap.Net.Runtime.Tests.csproj --verbosity m
  - cmd: dotnet restore ./ZapC.CSharp.Generator/ZapC.CSharp.Generator.csproj --verbosity m  
  - cmd: dotnet restore ./ZapC.CSharp.Generator.Tests/ZapC.CSharp.Generator.Tests.csproj --verbosity m  
  - cmd: dotnet restore ./ZapC.CSharp.MsBuild.Generation/ZapC.CSharp.MsBuild.Generation.csproj --verbosity m  
  - cmd: dotnet restore ./ZapC.CSharp.MsBuild.Generation.Tests/ZapC.CSharp.MsBuild.Generation.Tests.csproj --verbosity m  
  - cmd: dotnet restore ./zapc-csharp/zapc-csharp.csproj --verbosity m  
build_script:
  - cmd: msbuild ./Zap.Net.sln /p:Configuration="Debug" -V:m
  - cmd: msbuild ./Zap.Net.sln /p:Configuration="Release" -V:m
  - cmd: msbuild ./ZapCompatTest.sln /p:Configuration="Debug" -V:m
  - cmd: msbuild ./ZapCompatTest.sln /p:Configuration="Release" -V:m
  - ps: scripts\zapc-csharp-pack.ps1
after_build:
  # For once the build has completed
artifacts:
 - path: bin\Release\Zap.Net.Runtime.*.nupkg
   name: Zap.Net.Runtime
   type: NuGetPackage
 - path: bin\Release\ZapC.CSharp.MsBuild.Generation.*.nupkg
   name: ZapC.CSharp.MsBuild.Generation
   type: NuGetPackage
 - path: chocolatey\install\zapc-csharp-win-x86.*.nupkg
   name: zapc-csharp-win-x86
   type: NuGetPackage
 - path: chocolatey\install\zapc-csharp.*-deprecated.nupkg
   name: zapc-csharp-deprecated
   type: NuGetPackage
 - path: zapc-csharp\nupkg\*.nupkg
   name: zapc-csharp
   type: NuGetPackage
 - path: coverage
   name: Coverage report
   type: zip
test_script:
  - cmd: |
      nbgv get-version -v NuGetPackageVersion >> myversion.txt
      set /P VERSION=< myversion.txt
      vstest.console /logger:Appveyor /inIsolation ZapC.CSharp.Generator.Tests\bin\Release\netcoreapp3.1\ZapC.CSharp.Generator.Tests.dll
      cd %APPVEYOR_BUILD_FOLDER%\zapc-csharp
      dotnet tool install --global --add-source ./nupkg zapc-csharp --version %VERSION%
      cd %APPVEYOR_BUILD_FOLDER%\install-test
      compile-test
      cd %APPVEYOR_BUILD_FOLDER%
      vstest.console /logger:Appveyor /inIsolation ZapC.CSharp.Generator.Tests\bin\Release\netcoreapp3.1\ZapC.CSharp.Generator.Tests.dll
      dotnet tool uninstall --global zapc-csharp
      cd %APPVEYOR_BUILD_FOLDER%\install-test
      notinstalled-test
      cd %APPVEYOR_BUILD_FOLDER%\chocolatey\install
      choco install zap --source="https://chocolatey.org/api/v2" --force -y
      choco install zapc-csharp-win-x86 --source=".;https://chocolatey.org/api/v2" --force -y --version %VERSION% --pre
      cd %APPVEYOR_BUILD_FOLDER%\install-test
      compile-test
      choco uninstall zapc-csharp-win-x86 -y
      notinstalled-test
      cd %APPVEYOR_BUILD_FOLDER%
      vstest.console /logger:Appveyor /inIsolation ZapC.CSharp.MsBuild.Generation.Tests\bin\Release\netcoreapp3.1\ZapC.CSharp.MsBuild.Generation.Tests.dll
      msbuild -t:restore ./MsBuildGenerationTest/MsBuildGenerationTest.csproj /p:Configuration="Debug" /p:PackageReferenceVersion="%VERSION%"
      msbuild ./MsBuildGenerationTest/MsBuildGenerationTest.sln /p:Configuration="Debug" /p:PackageReferenceVersion="%VERSION%"
      vstest.console /logger:Appveyor /inIsolation Zap.Net.Runtime.Tests\bin\Debug\net471\Zap.Net.Runtime.Tests.dll
      vstest.console /logger:Appveyor /inIsolation Zap.Net.Runtime.Tests\bin\Release\netcoreapp3.1\Zap.Net.Runtime.Tests.dll
      powershell -File .\scripts\measure-coverage.ps1
      csmacnz.Coveralls --lcov -i "coverage\lcov.info" --repoToken %COVERALLS_REPO_TOKEN%
on_finish :
  # any cleanup in here
deploy:
  - provider: Environment
    name: GitHub Releases
    description: 'Deployed from CI.'
    artifact: /.*\.nupkg/
    draft: true
    prerelease: true
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true 
